### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by indotronic** [rousir/ArduinoVoip#1]
i am try and cannot connect to sip server!

**Comment by rousir** [comment]
What does the serial port output? Send log information. In what step it failed

**Comment by rousir** [comment]
I submitted a new modification, you can test it

**Comment by indotronic** [comment]
15:12:50.311 -> WIFISTA Connected
15:12:50.311 -> WIFISTA MAC: 3C:61:05:32:42:E8, IPv4: 192.168.43.54

still show it 

i am using raspberry for SIP server, and connect Handphone get IP 192.168.43.202
esp32 connect HP get IP 192.168.43.54

**Comment by rousir** [comment]
Is the sip information correct?Modify the `/src/Debug.h` file to view specific debugging information

**Comment by indotronic** [comment]
Show it now 👍 

15:20:41.455 -> sip server disconnected, reconnect...
15:20:41.455 -> sip server disconnected, reconnect...
15:20:41.455 -> sip server disconnected, reconnect...
15:20:41.502 -> sip server disconnected, reconnect...
15:20:41.502 -> sip server disconnected, reconnect...
15:20:41.502 -> sip server disconnected, reconnect...

String telNr = "2000";
String serverIp = "192.168.43.202";
String serverAgent = "192.168.43.202:5060";

String user = "2010";
String pwd  = "2010";

other softphone connect fine!

**Comment by rousir** [comment]
Sorry, I haven’t tested the Raspberry sip server. This library uses tcp to connect to the sip server. Is your pi sip server using tcp? You can install a [minisipserver ](https://www.myvoipapp.com/)on your computer and try it.

**Comment by indotronic** [comment]
Ok, now 👍 
7:01:27.665 ->  Connect SIP Server  Port 5060
17:01:27.665 ->  Connect SIP Client  on IP 192.168.43.202 Port 5060 ret= true
17:01:27.699 -> *****  Register  *****
17:01:27.699 -> REGISTER sip:192.168.43.202 SIP/2.0
17:01:27.699 -> Via: SIP/2.0/TCP 192.168.43.54:5060;branch=z9hG4bK-4Qv1Xg1Lf1Mj1Ra5Pt7Wk8Ux8Te1Xq
17:01:27.699 -> Max-Forwards: 70
17:01:27.699 -> From: <sip:2000@192.168.43.202:5060>;tag=4Oi8Oh1Mx2Tp8On8Tx2Br3Kk5Ac5Ti
17:01:27.699 -> To: <sip:2000@192.168.43.202:5060>
17:01:27.699 -> Call-ID: 6Hd0Cr0@192.168.43.202:5060
17:01:27.699 -> CSeq: 1 REGISTER
17:01:27.699 -> User-Agent: esp32 sip
17:01:27.699 -> Contact: <sip:2000@192.168.43.54;transport=TCP>
17:01:27.732 -> Allow: INVITE,ACK,OPTIONS,BYE,CANCEL,SUBSCRIBE,NOTIFY,REFER,MESSAGE,INFO,PING
17:01:27.732 -> Content-Length: 0
17:01:27.732 -> 
17:01:27.732 -> -_ SIP/2.0 401 Unauthorized

17:01:27.732 ->  Response Code               401
17:01:27.732 -> -_ Via: SIP/2.0/TCP 192.168.43.54:5060;branch=z9hG4bK-4Qv1Xg1Lf1Mj1Ra5Pt7Wk8Ux8Te1Xq;received=192.168.43.54

17:01:27.732 ->  sipHeaderR.via.port         5060
17:01:27.732 ->  sipHeaderR.via.branch       z9hG4bK-4Qv1Xg1Lf1Mj1Ra5Pt7Wk8Ux8Te1Xq
17:01:27.767 ->  sipHeaderR.via.userClient   192.168.43.54
17:01:27.767 -> -_ From: <sip:2000@192.168.43.202:5060>;tag=4Oi8Oh1Mx2Tp8On8Tx2Br3Kk5Ac5Ti

17:01:27.767 ->  sipHeaderR.from.telNr       2000
17:01:27.767 ->  sipHeaderR.from.userAgent   192.168.43.202
17:01:27.767 ->  sipHeaderR.from.tagFrom     4Oi8Oh1Mx2Tp8On8Tx2Br3Kk5Ac5Ti
17:01:27.767 -> -_ To: <sip:2000@192.168.43.202:5060>;tag=as2f286b27

17:01:27.767 ->  sipHeaderR.to.telNr         2000
17:01:27.767 ->  sipHeaderR.to.userAgent     192.168.43.202
17:01:27.800 ->  sipHeaderR.to.tagTo         as2f286b27
17:01:27.800 -> -_ Call-ID: 6Hd0Cr0@192.168.43.202:5060

17:01:27.800 ->  sipHeaderR.callId.callId    6Hd0Cr0@192.168.43.202:5060
17:01:27.800 -> -_ CSeq: 1 REGISTER

17:01:27.800 ->  sipHeaderR.Cseq.Cseq        1
17:01:27.800 ->  sipHeaderR.Cseq.userAgent   REGISTER
17:01:27.800 -> -_ Server: Asterisk PBX 16.2.1~dfsg-1+deb10u2

17:01:27.800 -> -_ Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE

17:01:27.834 -> -_ Supported: replaces, timer

17:01:27.834 -> -_ WWW-Authenticate: Digest algorithm=MD5, realm="asterisk", nonce="32e5e951"

17:01:27.834 ->  sipHeaderR.auth...realm     asterisk
17:01:27.834 ->  sipHeaderR.auth...domain    
17:01:27.834 ->  sipHeaderR.auth...nonce     32e5e951
17:01:27.834 ->  sipHeaderR.auth...stale     
17:01:27.834 ->  sipHeaderR.auth...algorithm MD5
17:01:27.834 ->  sipHeaderR.auth...qop       
17:01:27.834 -> -_ Content-Length: 0

17:01:27.834 ->  sipHeaderR.contentLength    0
17:01:27.834 -> -_ 

17:01:27.834 -> Execute 401 sipRegisterAuth
17:01:27.869 -> *****  Register Auth *****
17:01:27.869 -> REGISTER sip:192.168.43.202 SIP/2.0
17:01:27.869 -> Via: SIP/2.0/TCP 192.168.43.54:5060;branch=z9hG4bK-4Qv1Xg1Lf1Mj1Ra5Pt7Wk8Ux8Te1Xq
17:01:27.869 -> To: <sip:2000@192.168.43.202>
17:01:27.869 -> From: <sip:2000@192.168.43.202>;tag=4Oi8Oh1Mx2Tp8On8Tx2Br3Kk5Ac5Ti
17:01:27.869 -> Call-ID: 6Hd0Cr0@192.168.43.202:5060
17:01:27.869 -> CSeq: 2 REGISTER
17:01:27.869 -> Max-Forwards: 70
17:01:27.869 -> Expires: 120
17:01:27.869 -> Authorization: Digest username="2011",realm="asterisk",nonce="32e5e951",uri="sip:192.168.43.202",response="d79e56e366241de08ab1fa21f951f475",algorithm=MD5
17:01:27.904 -> Contact: <sip:2000@192.168.43.54;transport=TCP>
17:01:27.904 -> User-Agent: esp32 sip
17:01:27.904 -> Supported: replaces
17:01:27.904 -> Allow: INVITE,ACK,OPTIONS,BYE,CANCEL,SUBSCRIBE,NOTIFY,REFER,MESSAGE,INFO,PING
17:01:27.904 -> Allow-Events: presence,refer,telephone-event,keep-alive,dialog
17:01:27.904 -> Accept: application/sdp,application/dtmf-relay,text/plain
17:01:27.939 -> Content-Length: 0
17:01:27.939 -> 
17:01:27.939 -> *****  Register  Auth out *****
17:01:28.009 -> -_ SIP/2.0 403 Forbidden

17:01:28.043 ->  Response Code               403
17:01:28.043 -> -_ Via: SIP/2.0/TCP 192.168.43.54:5060;branch=z9hG4bK-4Qv1Xg1Lf1Mj1Ra5Pt7Wk8Ux8Te1Xq;received=192.168.43.54

17:01:28.043 ->  sipHeaderR.via.port         5060
17:01:28.043 ->  sipHeaderR.via.branch       z9hG4bK-4Qv1Xg1Lf1Mj1Ra5Pt7Wk8Ux8Te1Xq
17:01:28.043 ->  sipHeaderR.via.userClient   192.168.43.54
17:01:28.043 -> -_ From: <sip:2000@192.168.43.202>;tag=4Oi8Oh1Mx2Tp8On8Tx2Br3Kk5Ac5Ti

17:01:28.076 ->  sipHeaderR.from.telNr       2000
17:01:28.076 ->  sipHeaderR.from.userAgent   192.168.43.202
17:01:28.076 ->  sipHeaderR.from.tagFrom     4Oi8Oh1Mx2Tp8On8Tx2Br3Kk5Ac5Ti
17:01:28.076 -> -_ To: <sip:2000@192.168.43.202>;tag=as2f286b27

17:01:28.076 ->  sipHeaderR.to.telNr         2000
17:01:28.076 ->  sipHeaderR.to.userAgent     192.168.43.202
17:01:28.076 ->  sipHeaderR.to.tagTo         as2f286b27
17:01:28.076 -> -_ Call-ID: 6Hd0Cr0@192.168.43.202:5060

17:01:28.110 ->  sipHeaderR.callId.callId    6Hd0Cr0@192.168.43.202:5060
17:01:28.110 -> -_ CSeq: 2 REGISTER

17:01:28.110 ->  sipHeaderR.Cseq.Cseq        2
17:01:28.110 ->  sipHeaderR.Cseq.userAgent   REGISTER
17:01:28.110 -> -_ Server: Asterisk PBX 16.2.1~dfsg-1+deb10u2

17:01:28.110 -> -_ Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE

17:01:28.110 -> -_ Supported: replaces, timer

17:01:28.110 -> -_ Content-Length: 0

17:01:28.110 ->  sipHeaderR.contentLength    0
17:01:28.110 -> -_ 

17:01:28.143 -> Execute 403 Forbidden
17:01:28.143 -> Stop UDP read and Write
17:01:32.734 ->  Stop  SIP Client on IP 192.168.43.202 Port 5060
17:01:32.734 -> sip server disconnected, reconnect...
17:01:32.935 ->  Connect SIP Client  on IP 192.168.43.202 Port 5060 ret= true
17:01:32.935 -> *****  Register  *****
17:01:32.935 -> REGISTER sip:192.168.43.202 SIP/2.0
17:01:32.935 -> Via: SIP/2.0/TCP 192.168.43.54:5060;branch=z9hG4bK-4Qv1Xg1Lf1Mj1Ra5Pt7Wk8Ux8Te1Xq
17:01:32.969 -> Max-Forwards: 70
17:01:32.969 -> From: <sip:2000@192.168.43.202:5060>;tag=4Oi8Oh1Mx2Tp8On8Tx2Br3Kk5Ac5Ti
17:01:32.969 -> To: <sip:2000@192.168.43.202:5060>
17:01:32.969 -> Call-ID: 6Hd0Cr0@192.168.43.202:5060
17:01:32.969 -> CSeq: 1 REGISTER
17:01:32.969 -> User-Agent: esp32 sip
17:01:32.969 -> Contact: <sip:2000@192.168.43.54;transport=TCP>
17:01:32.969 -> Allow: INVITE,ACK,OPTIONS,BYE,CANCEL,SUBSCRIBE,NOTIFY,REFER,MESSAGE,INFO,PING
17:01:32.969 -> Content-Length: 0
17:01:32.969 -> 
17:01:32.969 -> -_ SIP/2.0 500 Server error

17:01:32.969 ->  Response Code               500
17:01:33.003 -> -_ Via: SIP/2.0/TCP 192.168.43.54:5060;branch=z9hG4bK-4Qv1Xg1Lf1Mj1Ra5Pt7Wk8Ux8Te1Xq;received=192.168.43.54

17:01:33.003 ->  sipHeaderR.via.port         5060
17:01:33.003 ->  sipHeaderR.via.branch       z9hG4bK-4Qv1Xg1Lf1Mj1Ra5Pt7Wk8Ux8Te1Xq
17:01:33.003 ->  sipHeaderR.via.userClient   192.168.43.54
17:01:33.003 -> -_ From: <sip:2000@192.168.43.202:5060>;tag=4Oi8Oh1Mx2Tp8On8Tx2Br3Kk5Ac5Ti

17:01:33.003 ->  sipHeaderR.from.telNr       2000
17:01:33.038 ->  sipHeaderR.from.userAgent   192.168.43.202
17:01:33.038 ->  sipHeaderR.from.tagFrom     4Oi8Oh1Mx2Tp8On8Tx2Br3Kk5Ac5Ti
17:01:33.038 -> -_ To: <sip:2000@192.168.43.202:5060>;tag=as2f286b27

17:01:33.038 ->  sipHeaderR.to.telNr         2000
17:01:33.038 ->  sipHeaderR.to.userAgent     192.168.43.202
17:01:33.038 ->  sipHeaderR.to.tagTo         as2f286b27
17:01:33.038 -> -_ Call-ID: 6Hd0Cr0@192.168.43.202:5060

17:01:33.038 ->  sipHeaderR.callId.callId    6Hd0Cr0@192.168.43.202:5060
17:01:33.038 -> -_ CSeq: 1 REGISTER

17:01:33.072 ->  sipHeaderR.Cseq.Cseq        1
17:01:33.072 ->  sipHeaderR.Cseq.userAgent   REGISTER
17:01:33.072 -> -_ Server: Asterisk PBX 16.2.1~dfsg-1+deb10u2

17:01:33.072 -> -_ Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE

17:01:33.072 -> -_ Supported: replaces, timer

17:01:33.072 -> -_ Content-Length: 0

17:01:33.072 ->  sipHeaderR.contentLength    0
17:01:33.072 -> -_ 

17:01:33.072 -> 500 does not Exists :-)
17:01:37.992 ->  Stop  SIP Client on IP 192.168.43.202 Port 5060
17:01:37.992 -> sip server disconnected, reconnect...
17:01:37.992 ->  Connect SIP Client  on IP 192.168.43.202 Port 5060 ret= true
17:01:37.992 -> *****  Register  *****
17:01:37.992 -> REGISTER sip:192.168.43.202 SIP/2.0
17:01:37.992 -> Via: SIP/2.0/TCP 192.168.43.54:5060;branch=z9hG4bK-4Qv1Xg1Lf1Mj1Ra5Pt7Wk8Ux8Te1Xq
17:01:38.025 -> Max-Forwards: 70
17:01:38.025 -> From: <sip:2000@192.168.43.202:5060>;tag=4Oi8Oh1Mx2Tp8On8Tx2Br3Kk5Ac5Ti
17:01:38.025 -> To: <sip:2000@192.168.43.202:5060>
17:01:38.025 -> Call-ID: 6Hd0Cr0@192.168.43.202:5060
17:01:38.025 -> CSeq: 1 REGISTER
17:01:38.025 -> User-Agent: esp32 sip
17:01:38.025 -> Contact: <sip:2000@192.168.43.54;transport=TCP>
17:01:38.025 -> Allow: INVITE,ACK,OPTIONS,BYE,CANCEL,SUBSCRIBE,NOTIFY,REFER,MESSAGE,INFO,PING
17:01:38.025 -> Content-Length: 0

**Comment by indotronic** [comment]
17:30:20.900 -> *****  Register  Auth out *****
17:30:20.900 -> -_ SIP/2.0 200 OK

17:30:20.900 ->  Response Code               200
17:30:20.900 -> -_ Via: SIP/2.0/TCP 192.168.43.54:5060;branch=z9hG4bK-1Ef7Wl2Af3Ct8Oy8Gn3Ha6At2Rb5Aj;received=192.168.43.54

17:30:20.900 ->  sipHeaderR.via.port         5060
17:30:20.900 ->  sipHeaderR.via.branch       z9hG4bK-1Ef7Wl2Af3Ct8Oy8Gn3Ha6At2Rb5Aj
17:30:20.900 ->  sipHeaderR.via.userClient   192.168.43.54
17:30:20.900 -> -_ From: <sip:2011@192.168.43.202>;tag=6Hf8Ex1Ks5Ne4Nv2Ox1Ey8Xs8Fh1Ud

17:30:20.947 ->  sipHeaderR.from.telNr       2011
17:30:20.947 ->  sipHeaderR.from.userAgent   192.168.43.202
17:30:20.947 ->  sipHeaderR.from.tagFrom     6Hf8Ex1Ks5Ne4Nv2Ox1Ey8Xs8Fh1Ud
17:30:20.947 -> -_ To: <sip:2011@192.168.43.202>;tag=as4aa1fe85

17:30:20.947 ->  sipHeaderR.to.telNr         2011
17:30:20.947 ->  sipHeaderR.to.userAgent     192.168.43.202
17:30:20.947 ->  sipHeaderR.to.tagTo         as4aa1fe85
17:30:20.947 -> -_ Call-ID: 6Sb2It4@192.168.43.202:5060

17:30:20.947 ->  sipHeaderR.callId.callId    6Sb2It4@192.168.43.202:5060
17:30:20.947 -> -_ CSeq: 2 REGISTER

17:30:20.947 ->  sipHeaderR.Cseq.Cseq        2
17:30:20.947 ->  sipHeaderR.Cseq.userAgent   REGISTER
17:30:20.947 -> -_ Server: Asterisk PBX 16.2.1~dfsg-1+deb10u2

17:30:20.994 -> -_ Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE

17:30:20.994 -> -_ Supported: replaces, timer

17:30:20.994 -> -_ Expires: 120

17:30:20.994 -> -_ Contact: <sip:2011@192.168.43.54;transport=TCP>;expires=120

17:30:20.994 ->  contact.telNr               2011
17:30:20.994 ->  contact.userClient          192.168.43.54
17:30:20.994 ->  contact.expires             120
17:30:20.994 -> -_ Date: Thu, 04 Mar 2021 10:30:18 GMT

17:30:20.994 -> -_ Content-Length: 0

17:30:20.994 ->  sipHeaderR.contentLength    0
17:30:20.994 -> -_ 

17:30:20.994 -> Execute 200 OK Register
17:30:20.994 -> REGISTER OK


SEEM OK NOW>> lets me try to making call!

**Comment by indotronic** [comment]
work, but if incoming call and hang up still show 
UDP write TRUE count  172  TRUE  Sequence Number : 2855 Timestamp: 299313 ADDR: 192.168.43.202 on Port 10206
21:43:59.333 -> Nr. of parsePacket: 0 Byte

**Comment by indotronic** [comment]
08:46:43.992 -> Execute ACK
08:46:43.992 -> Start UDPTRUE on Port 17006
08:46:43.992 -> E (34647) I2S: /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/driver/i2s.c:1325 (i2s_read):rx NULL

**Comment by indotronic** [comment]
working now.. :D 
if from caller hangup, esp32 cannot hangup?

**Comment by rousir** [comment]
You can hang up, mainly depends on whether the esp32 has received the hang up packet normally
